<div id="wrap" class="reg">
		<form  action="/User/Index/order" method="post" class="jClever" enctype="multipart/form-data" >
			<h1 class="header">Заказ работы</h1>
			<div class="wrap">
				<?php if( !empty($this->error) ):?>
					<p class="errormsg"><?php echo $this->error;?></p>
				<?php elseif ( !empty($this->success) ):?>
					<p class="errormsg success"><?php echo $this->success;?></p>
				<?php endif;?>
				<div class="reg-user">
					<h2 class="header">Обязательные поля</h2>
					<label>Тема работы<sup>*</sup></label><br>
					<input name="orderName" type="text" placeholder="Введите тему вашей работы"><br>
					<label>Предмет<sup>*</sup></label><br>
					<select name="predmet" id="">
						<option value="APP|Автоматизация производственных процессов (АПП)">Автоматизация производственных процессов (АПП)</option>
						<option value="Anatomiya|Анатомия">Анатомия</option>
						<option value="AngliyskiyYazik|Английский язык">Английский язык</option>
						<option value="AntikrizisnoeUpravlenie|Антикризисное управление">Антикризисное управление</option>
						<option value="Arhitektura|Архитектура">Архитектура</option>
						<option value="Astronomiya|Астрономия">Астрономия</option>
						<option value="AuditBuhgalterskiyIUpravlencheskiyUchet|Аудит, бухгалтерский и управленческий учет">Аудит, бухгалтерский и управленческий учет</option>
						<option value="AHD|Анализ хозяйственной деятельности">Анализ хозяйственной деятельности</option>
						<option value="BankovskiyIInvesticionniyMenedzhment|Банковский и инвестиционный менеджмент">Банковский и инвестиционный менеджмент</option>
						<option value="BankovskoeDelo|Банковское дело">Банковское дело</option>
						<option value="BZHD|Безопасность жизнедеятельности">Безопасность жизнедеятельности</option>
						<option value="BiznessPlanirovanie|Бизнес планирование">Бизнес-планирование</option>
						<option value="Biologiya|Биология">Биология</option>
						<option value="BuhuchetStatistika|Бухучет, статистика">Бухучет, статистика</option>
						<option value="VSTI|Взаимозаменяемость, Стандартизация, Технические измерения">Взаимозаменяемость, Стандартизация, Технические измерения</option>
						<option value="VED|Внешняя эконом деятельность">Внешняя эконом деятельность</option>
						<option value="Geografiya|География">География</option>
						<option value="Geodeziya|Геодезия">Геодезия</option>
						<option value="Geopolitika|Геополитика">Геополитика</option>
						<option value="Gidravlika|Гидравлика">Гидравлика</option>
						<option value="GostinichnoeDelo|Гостиничное дело">Гостиничное дело</option>
						<option value="GrazhdanskoePravo|Граждансое право">Граждансое право</option>
						<option value="Deloproizvodstvo|Делопроизводство">Делопроизводство</option>
						<option value="DengiKreditBanki|Деньги, кредит, банки">Деньги, кредит, банки</option>
						<option value="DetaliMashin|Детали машин">Детали машин</option>
						<option value="Dizain|Дизайн">Дизайн</option>
						<option value="DoshkolnayaPedagogika|Дошкольная педагогика">Дошкольная педагогика</option>
						<option value="ZhilishnoePravo|Жилищное право">Жилищное право</option>
						<option value="Zhurnalistika|Журналистика">Журналистика</option>
						<option value="ZemelnoePravo|Земельное право">Земельное право</option>
						<option value="InvesticionniyMenedzhment|Инвестиционный менеджмент">Инвестиционный менеджмент</option>
						<option value="Investicii|Инвестиции">Инвестиции</option>
						<option value="InzhenernayaGrafika|Инженерная графика">Инженерная графика</option>
						<option value="InostrannieYaziki|Иностранные языки">Иностранные языки</option>
						<option value="InformatikaIProgrammirovanie|Информатика и программирование">Информатика и Программирование</option>
						<option value="Istoriya|История">История</option>
						<option value="KommercheskayaDeyatelnost|Коммерческая деятельность">Коммерческая деятельность</option>
						<option value="Konfliktologiya|Конфликтология">Конфликтология</option>
						<option value="Kriminalistika|Криминалистика">Криминалистика</option>
						<option value="Kulinariya|Кулинария">Кулинария</option>
						<option value="KulturaIIskusstvo|Культура и искуство">Культура и искуство</option>
						<option value="Kulturologiya|Культурология">Культурология</option>
						<option value="Lingvistika|Лингвистика">Лингвистика</option>
						<option value="Literatura|Литература">Литература</option>
						<option value="Logika|Логика">Логика</option>
						<option value="Logistika|Логистика">Логистика</option>
						<option value="Logopediya|Логопедия">Логопедия</option>
						<option value="Makroekonomika|Макроэкономика">Макроэкономика</option>
						<option value="Marketing|Маркетинг">Маркетинг</option>
						<option value="Matematika|Математика">Математика</option>
						<option value="Medicina|Медицина">Медицина</option>
						<option value="MezhdunarodnieOtnosheniya|Международные отношения">Международные отношения</option>
						<option value="Menedzhment|Менеджмент">Менеджмент</option>
						<option value="Mehanika|Механика">Механика</option>
						<option value="Mikroekonomika|Микроэкономика">Микроэкономика</option>
						<option value="MunicipalnoePravo|Муницепальное право">Муницепальное право</option>
						<option value="Nalogi|Налоги">Налоги</option>
						<option value="NemeckiyYazik|Немецкий язык">Немецкий язык</option>
						<option value="OrganizaciyaTrudaIProizvodstvo|Организация труда и производство">Организация труда и производство</option>
						<option value="OsnoviKonstruiroravaniya|Основы конструирования">Основы конструирования</option>
						<option value="OsnoviPredprinimatelstva|Основы предпринимательства">Основы предпринимательства</option>
						<option value="OhranaPrirodi|Охрана природы">Охрана природы</option>
						<option value="OhranaTruda|Охрана труда">Охрана труда</option>
						<option value="Pedagogika|Педагогика">Педагогика</option>
						<option value="Politologiya|Политология">Политология</option>
						<option value="Pravo|Право">Право</option>
						<option value="Predprinimatelstvo|Предпринимательство">Предпринимательство</option>
						<option value="Promishlennost|Промышленность">Промышленность</option>
						<option value="ProcessiIApparatiPishevoiPromishlennosti|Процессы и аппараты пищевой промышленности">Процессы и аппараты пищевой промышленности</option>
						<option value="Psihologiya|Психология">Психология</option>
						<option value="RadiosvazIRadiotehnika|Радиосвязь и радиотехника">Радиосвязь и радиотехника</option>
						<option value="Raznoe|Разное">Разное</option>
						<option value="PeklamaPR|Реклама, PR">Реклама, PR</option>
						<option value="RusskiyYazikILiteratura|Русский язык и литература">Русский язык и литература</option>
						<option value="SelskoeHozyaistvo|Сельское хозяйство">Сельское хозяйство</option>
						<option value="SistemiPeredachiISistemiKommutacii|Системы передачи и системы коммутации">Системы передачи и системы коммутации</option>
						<option value="Sopromat|Сопромат">Сопромат</option>
						<option value="SocialnayaRabota|Социальная работа">Социальная работа</option>
						<option value="Sociologiya|Социология">Социология</option>
						<option value="SportITurizm|Спорт и туризм">Спорт и туризм</option>
						<option value="Statistika|Статистика">Статистика</option>
						<option value="StrategicheskiyMarketing|Стратегический маркетинг">Стратегический маркетинг</option>
						<option value="StrategicheskiyMenedzhment|Стратегический менеджмент">Стратегический менеджмент</option>
						<option value="Strahovanie|Страхование">Страхование</option>
						<option value="Stroitelstvo|Строительство">Строительство</option>
						<option value="SudebnayaBuhgaltiriya|Судебная бухгалтерия">Судебная бухгалтерия</option>
						<option value="Telekommunikaciya|Телекоммуникация">Телекоммуникация</option>
						<option value="TeoreticheskayaMehanika|Теоретическая механика">Теоретическая механика</option>
						<option value="TeoriyaGosudarstvaIPrava|Теория государства и права">Теория государства и права</option>
						<option value="TeoriyaMashinIMehanizmov|Теория машин и механизмов (ТММ)">Теория машин и механизмов (ТММ)</option>
						<option value="Teplotehnika|Теплотехника">Теплотехника</option>
						<option value="Teploenergetika|Теплоэнергетика">Теплоэнергетика</option>
						<option value="Tehnicheskie|Технические">Технические</option>
						<option value="TehnologiyaMashinostroeniya|Технология машиностроения">Технология машиностроения</option>
						<option value="Tovarovedenie|Товароведение">Товароведение</option>
						<option value="Turizm|Туризм">Туризм</option>
						<option value="UgolovnoePravo|Уголовное право">Уголовное право</option>
						<option value="UgolovniyProcess|Уголовный процесс">Уголовный процесс</option>
						<option value="UkrainskiyYazikILiteratura|Украинский язык и литература">Украинский язык и литература</option>
						<option value="UpravlenieZatratami|Управление затратами">Управление затратами</option>
						<option value="UpravlenieLogistikoi|Управление логистикой">Управление логистикой</option>
						<option value="UpravleniePersonalom|Управление персоналом">Управление персоналом</option>
						<option value="UpravlenieProektami|Управление проектами">Управление проектами</option>
						<option value="UpravlenieIssledovaniyami|Управление исследованиями">Управление исследованиями</option>
						<option value="UpravlencheskiyUchet|Управленческий учет">Управленческий учет</option>
						<option value="Fizika|Физика">Физика</option>
						<option value="FizkulturaISport|Физкультура и спорт">Физкультура и спорт</option>
						<option value="Filologiya|Филология">Филология</option>
						<option value="Filosofiya|Философия">Философия</option>
						<option value="FinansoviyAnaliz|Финансовый анализ">Финансовый анализ</option>
						<option value="FinansiIKredit|Финансы и кредит">Финансы и кредит</option>
						<option value="FrancuzskiyYazik|Французский язык">Французский язык</option>
						<option value="Himiya|Химия">Химия</option>
						<option value="CeniICenoobrazovanie|Цены и ценообразование">Цены и ценообразование</option>
						<option value="Cherchenie|Черчение">Черчение</option>
						<option value="Ekologiya|Экология">Экология</option>
						<option value="Ekonomika|Экономика">Экономика</option>
						<option value="EkonomikaPredpriyatiya|Экономика предприятия">Экономика предприятия</option>
						<option value="EkonomicheskayaTeoriya|Экономическая теория">Экономическая теория</option>
						<option value="EkonomicheskieDisciplini|Экономические дисциплины">Экономические дисциплины</option>
						<option value="EkonomicheskiyAnaliz|Экономический анализ">Экономический анализ</option>
						<option value="Ekskursovedenie|Экскурсоведение">Экскурсоведение</option>
						<option value="ElektronikaIRadiotehnika|Электроника и радиотехника">Электроника и радиотехника</option>
						<option value="Elektrotehnika|Электротехника">Электротехника</option>
						<option value="Elektroenergetika|Электроэнергетика">Электроэнергетика</option>
						<option value="Energetika|Энергетика">Энергетика</option>
						<option value="Energosnabzhenie|Энергоснабжение">Энергоснабжение</option>
						<option value="EtikaIEstetika|Этика и эстетика">Этика и эстетика</option>
						<option value="UridicheskieDisciplini|Юридические дисциплины">Юридические дисциплины</option>
						<option value="Urisprudenciya|Юриспруденция">Юриспруденция</option>
					</select>
					<label>Тип работы<sup>*</sup></label><br>
					<select name="predmetType">
						<option value="0">Выберите тип работы</option>
						<option value="Автореферат">Автореферат</option>
						<option value="Дипломная работа">Дипломная работа</option>
						<option value="Дипломная работа MBA">Дипломная работа MBA</option>
						<option value="Диссертация">Диссертация</option>
						<option value="Доклад">Доклад</option>
						<option value="Контрольная работа">Контрольная работа</option>
						<option value="Курсовая работа">Курсовая работа</option>
						<option value="Магистерская работа">Магистерская работа</option>
						<option value="Ответы на билеты">Ответы на билеты</option>
						<option value="Отчёт по практике">Отчёт по практике</option>
						<option value="Перевод">Перевод</option>
						<option value="Презентация">Презентация</option>
						<option value="Реферат">Реферат</option>
						<option value="Статьи к диссертации">Статьи к диссертации</option>
						<option value="Эссе">Эссе</option>
					</select>
					<label>Объем работы<sup>*</sup></label><br>
					<input name="orderCount" type="Text" placeholder="Количество страниц в работе"><br>
					<label>Количество источников<sup>*</sup></label><br>
					<input name="listSource" type="text" placeholder="Количество источников, которое необходимо использовать в работе"><br>
					<label>Срок выполнения<sup>*</sup></label><br>
					<input name="orderDtEnd" id="datepicker" type="text" placeholder="Дата, в которую вы хотите получить вашу работу" readonly><br>
					<script>
					    $(function() {
					    	$( "#datepicker" ).datepicker();
					    });
					</script>
					<label>Прикрепляемый файл</label><br>
					<input name="file" type="file"><br>
				</div>
				<div class="reg-user">
					<h2 class="header">Контактная информация</h2>
					<label>Фамилия, имя, отчество<sup>*</sup></label><br>
					<input name="customerName" type="text" placeholder="Введите фамилию, имя и отчество"><br>
					<label>Email<sup>*</sup></label><br>
					<input name="customerEmail" type="text" placeholder="Введите ваш электронный почтовый ящик"><br>
					<label>Номер мобильного телефона<sup>*</sup></label><br>
					<input name="cutomerPhone" type="text" placeholder="Введите номер вашего мобильного телефона"><br>
					<label>Предполагаемый бюджет<sup>*</sup></label><br>
					<input name="budget" type="text" placeholder="Введите предполагаемую сумму, которую вы хотите потратить на заказ"><br>
					<label>Дополнительные требования </label><br>
					<textarea name="addInf" placeholder="Ваши комментарии и пожелания" rows="11" class="cleararea"></textarea>
					<?php if( isset($_SESSION['site']) ):?>
						<input type="hidden" id="site" name="site" value="<?php echo $_SESSION['site']?>">
					<?php else : ?>
						<input type="hidden" id="site" name="site" value="http://www.diplomkin.com.ua/">
					<?php endif?>
					<input name="order" type="submit" value="Оформить">
				</div>
			</div>
		</form>
	</div>