<script type="text/javascript">

function ShowOrder(id)
{
	var order = <?php echo json_encode($this->orders);?>;
	$('#orderName').attr('value', order[id]['oderName']);
	$('#orderPredmet').attr('value',order[id]['predmet']);
	$('#OrderType').attr('value',order[id]['predmetType']);
	$('#orderCount').attr('value',order[id]['orderCount']);
	$('#orderListSource').attr('value',order[id]['listSource']);
	$('#orderDtEnd').attr('value',order[id]['orderDtEnd']);
	$('#orderAddInform').text(order[id]['orderAddInform']);
	$('#customerEmail').attr('value',order[id]['customerEmail']);
	$('#customerPhone').attr('value',order[id]['customerPhone']);
	$('#customerName').attr('value',order[id]['customerName']);
	$('#orderID').attr('value',id);
}

function EditOrder(id,form)
{
	var data = "";
	for(var i=0; i<form.length;i++){
		var val = form [i].value;
		var v = form [i].name;
		data = data + "&"+v+"="+val;
	}
	$.ajax({
        type: "POST",
        url: 'http://zf2-tutorial.localhost/User/Index/orderlist/',
        data: "ajax=1"+data,
        success: function(msg)
        {
            if ( msg == 'OK' ) { self.location.reload(); return false; }
            else if ( msg == 'CAPTCHA' ) { alert("!"); self.location = '<%$sitePath%>account/login.html'; }
            else if ( msg.substr(0, 6) == 'ERROR:' )
            {
                $("#flogin_error").text('Ошибка! '+msg.substr(6));
                form.email.className = 'error';
                form.password.className = 'error';
                $(".error.pass").text('Неверный  E-mail или пароль').addClass("show");
            }
            else $("#flogin_error").text('Ошибка авторизации');

            form['but'].disabled = false;
            $('body').removeClass('wait');
        },
        error: function()
        {

        }
    });
}
</script>
<div id="wrap">
	<div class="popupBg" onClick="userEditToggle()"></div>
	<div id="uEditModal" class="modal">
		<form action="" class="jClever" method="post">
			<div class="field-block">
				<h2 class="header">Данные заказа</h2>
				<label>Тема работы</label><br>
				<input name="orderName" id="orderName" type="text" value=""><br>
				<label>Предмет</label><br>
				<input name="orderPredmet" id="orderPredmet" type="text" value=""><br>
				<label>Тип работы</label><br>
				<input name="OrderType" id="OrderType" type="text" value=""><br>
				<label>Объем работы</label><br>
				<input name="orderCount" id="orderCount" type="text" value=""><br>
				<label>Кол-во источиков</label><br>
				<input name="orderListSource" id="orderListSource" type="text" value=""><br>
				<label>Dead Line</label><br>
				<input name="orderDtEnd" id="orderDtEnd" type="text" value=""><br>
			</div>
			<div class="field-block">
				<h2 class="header">О заказчике</h2>
				<label>Фамилия, имя, отчество</label><br>
				<input name="customerName" id="customerName" type="text" value=""><br>
				<label>Email</label><br>
				<input name="customerEmail" id="customerEmail" type="text" value=""><br>
				<label>Номер мобильного</label><br>
				<input name="customerPhone" id="customerPhone" type="text" value="" disabled><br>
				<label>Доп. требования</label><br>
				<textarea name="orderAddInform" id="orderAddInform" name="address" rows="11"></textarea>
			</div>
			<div class="clear"></div>
			<div id="qew" class="field-block extended">
				<input type="hidden" id="orderID" >
				<input type="button" value="Изменить данные" onclick="EditOrder(this.form.orderID.value,this.form)"><br>
			</div>
		</form>
	</div>
		<div id="header">
			<a href="<?php echo $this->url("/User/Index/main");?>" class="logo">Dipsverka</a>
			<div class="user-menu">
				<div class="cabinet">
					<a href="#" class="man">Administrator</a>
					<ul class="drop-menu">
						<li><a href="<?php echo $this->url("/User/Index/Search");?>">Расширеный поиск</a></li>


						<?php /*<li><a href="#">Very Long Text Of The Link</a></li>
						<li><a href="#">Very Long Text Of The Link And Even More</a></li>*/?>


					</ul>
				</div>
				<a href="" class="gear" title="Опции">Опции</a>
				<a href="/User/Index/logout" class="lock" title="Выйти">Выйти</a>
			</div>
		</div>
		<div id="main">
			<div class="control-panel clearfix">
				<a href="#" class="plus">Добавить<br></a>
				<a href="#" class="minus">Удалить</a>
				<a href="#" class="trash">Корзина</a>
				<div class="search flr">
					<form name="search" action="<?php echo $this->url("/User/Index/orderlist")?>" method="GET">
						<div>
							<?php if(isset($this->searchActive)):?>
								<a href="<?php echo $this->url("/User/Index/orderlist");?>" class="del">Сбросить поиск</a>
							<?php endif;?>
							<input name="search" type="search" placeholder="Поиск...">
							<input  type="submit" value="" id="search">
						</div>
					</form>
				</div>
			</div>
			<form class="jClever">
				<table class="users">
					<thead>
						<tr>
							<th colspan="11">
								Пользователи сайта
							</th>
						</tr>
						<tr>
							<th class="check">
								<input type="checkbox" name="selectAll">
							</th>
							<th class="orderid">ID заказа</th>
							<th class="theme">Тема</th>
							<th class="course">Предмет</th>
							<th class="ordrType">Тип работы</th>
							<th class="ordrName">ФИО заказчика</th>
							<th class="indate">Дата заказа</th>
							<th class="expDate">Dead Line</th>
							<th class="volume">Объем</th>
							<th class="uedit">&nbsp;</th>
						</tr>
					</thead>
					<tfoot>
						<tr>
							<th colspan="11">
								<input type="text" name="page" placeholder="1">
							</th>
						</tr>
					</tfoot>
					<tbody>
					<?php if ( !empty($this->orders) ):?>
						<?php foreach ($this->orders as $key=>$val):?>
						<tr>
							<td>
								<input type="checkbox" name="check1">
							</td>
							<td><?php echo $val['orderID']?></td>
							<td><?php echo $val['oderName']?></td>
							<td><?php echo $val['predmet']?></td>
							<td><?php echo $val['predmetType']?></td>
							<td><?php echo $val['customerName']?></td>
							<td><?php echo $val['orderDtAdd']?></td>
							<td><?php echo $val['orderDtEnd']?></td>
							<td><?php echo $val['orderCount']?></td>
							<td><span id="<?php echo $key;?>" class="edit" onClick="ShowOrder(this.id);userEditToggle(true)"></span></td>
						</tr>
						<?php endforeach;?>
					<?php endif;?>
					</tbody>
				</table>
			</form>
		</div>
		<div id="footer"></div>
	</div>