<script type="text/javascript">

function ShowOrder(id)
{
	var order = <?php echo json_encode($this->orders);?>;
	$('#orderName').attr('value',order[id]['orderName'])
	$('#orderPredmet').attr('value',order[id]['predmet']);
	$('#OrderType').attr('value',order[id]['predmetType']);
	$('#orderCount').attr('value',order[id]['orderCount']);
	$('#orderListSource').attr('value',order[id]['listSource']);
	$('#orderDtEnd').attr('value',order[id]['orderDtEnd']);
	$('#orderAddInform').text(order[id]['orderAddInform']);
	$('#customerEmail').attr('value',order[id]['customerEmail']);
	$('#customerPhone').attr('value',order[id]['customerPhone']);
	$('#customerName').attr('value',order[id]['customerName']);
	$('#orderID').attr('value',order[id]['orderID']);
	$('#site').attr('value',order[id]['orderGetSite'])
	$('#orderButget').attr('value',order[id]['orderButget']);

	$('#orderFile').attr('value',"<?php echo $this->url("/files/")?>" + order[id]['orderFile']);
}

function EditOrder(id,form,m)
{
	var orderID = $('#orderID').attr('value');
	var data = "";
	for(var i=0; i<form.length;i++){
		var val = form [i].value;
		var v = form [i].name;
		data = data + "&"+v+"="+val;
	}/*feexme orderID*/
	if(m == 1)
	$.ajax({ 
        type: "POST",
        url: '<?php echo $this->url("/User/Index/orderlist/")?>',
        data: "ajax=edit&orderID="+orderID+data,
        success: function(msg)
        {
        	if(msg == "OK")
        		location.reload();
        },
        error: function()
        {
        		alert('плохая связь с сервером')
        }
    });
if(m == 2)
	$.ajax({ 
        type: "POST",
        url: '<?php echo $this->url("/User/Index/orderlist/")?>',
        data: "ajax=delete&orderID="+orderID+data,
        success: function(msg)
        {
        	if(msg == "OK")
        		location.reload();
        },
        error: function()
        {
        		alert('плохая связь с сервером')
        }
    });
}
</script>
<div id="wrap">
	<div class="popupBg" onClick="userEditToggle()"></div>
	<div id="uEditModal" class="modal">
		<form action="" class="jClever" method="post">
			<div class="field-block">
				<h2 class="header">Данные заказа</h2>
				<div>
					<label>Тема работы</label><br>
					<input name="orderName" id="orderName" type="text" value=""><br>
					<label>Предмет</label><br>
					<input name="orderPredmet" id="orderPredmet" type="text" value=""><br>
					<label>Тип работы</label><br>
					<input name="OrderType" id="OrderType" type="text" value=""><br>
					<label>Объем работы</label><br>
					<input name="orderCount" id="orderCount" type="text" value=""><br>
					<label>Кол-во источиков</label><br>
					<input name="orderListSource" id="orderListSource" type="text" value=""><br>
				</div>
				<div>
					<label>Dead Line</label><br>
					<input name="orderDtEnd" id="orderDtEnd" type="text" value=""><br>
					<label>Источник заказа</label><br>
					<input id="site" type="text" value=""><br>
					<label>Предпологаемый бюджет</label><br>
					<input name="orderButget" id="orderButget" type="text" value=""><br>
					<label>Ссылка на скачивание прикрепленного файла</label><br>
					<input name="orderFile" id="orderFile" type="text" value=""><br>
				</div>
			</div>
			<div class="field-block">
				<h2 class="header">О заказчике</h2>
				<label>Фамилия, имя, отчество</label><br>
				<input name="customerName" id="customerName" type="text" value=""><br>
				<label>Email</label><br>
				<input name="customerEmail" id="customerEmail" type="text" value=""><br>
				<label>Номер мобильного</label><br>
				<input name="cutomerPhone" id="customerPhone" type="text" value=""><br>
				<label>Доп. требования</label><br>
				<!-- Fixme лажа с высотой -->
				<textarea name="orderAddInform" id="orderAddInform" name="address" rows="7"></textarea>
				<input type="hidden" id="orderID" >
			</div>
			<div class="clear"></div>
			<div id="qew" class="field-block extended">
				<input type="button" value="Изменить данные" onclick="EditOrder(this.form.orderID.value,this.form,1)"><br>
				<input type="button" value="Удалить заказ" onclick="EditOrder(this.form.orderID.value,this.form,2)"><br>

			</div>
		</form>
	</div>
		<div id="header">
			<a href="<?php echo $this->url("/User/Index/main");?>" class="logo">Dipsverka</a>
			<div class="user-menu">
				<div id="cabinet" class="cabinet">
					<a href="#" class="man">Administrator</a>
					<ul class="drop-menu">
						<li><a id="aNewUser" href="<?php echo $this->url('/User/Index/newUser')?>"><span id="newUser"></span></a></li>
						<li><a id="aNewTask" href="<?php echo $this->url('/User/Order/newOrder')?>"><span id="newTask"></span></a></li>
						<li><a href="<?php echo $this->url("/User/Index/Search");?>">Расширеный поиск</a></li>
						<li><a href="<?php echo $this->url("/User/Index/orderlist");?>">Заказы</a></li>
					</ul>
					<span class="newbadge">NEW!</span>
				</div>
				<a href="" class="gear" title="Опции">Опции</a>
				<a href="/User/Index/logout" class="lock" title="Выйти">Выйти</a>
			</div>
		</div>
		<div id="main">
			<div class="control-panel clearfix">
				<a href="#" class="plus">Добавить<br></a>
				<a href="#" class="minus">Удалить</a>
				<a href="#" class="trash">Корзина</a>
				<div class="search flr">
					<form name="search" action="<?php echo $this->url("/User/Index/orderlist")?>" method="GET">
						<div>
							<?php if(isset($this->searchActive)):?>
								<a href="<?php echo $this->url("/User/Index/orderlist");?>" class="del">Сбросить поиск</a>
							<?php endif;?>
							<input name="search" type="search" placeholder="Поиск...">
							<input  type="submit" value="" id="search">
						</div>
					</form>
				</div>
			</div>
			<form class="jClever">
				<table class="users">
					<thead>
						<tr>
							<th colspan="11">
								Пользователи сайта
							</th>
						</tr>
						<tr>
							<th class="check">
								<input type="checkbox" name="selectAll">
							</th>
							<th class="orderid">ID заказа</th>
							<th class="theme">Тема</th>
							<th class="course">Предмет</th>
							<th class="ordrType">Тип работы</th>
							<th class="ordrName">ФИО заказчика</th>
							<th class="indate">Дата заказа</th>
							<th class="expDate">Dead Line</th>
							<th class="volume">Объем</th>
							<th class="uedit">&nbsp;</th>
						</tr>
					</thead>
					<tfoot>
						<tr>
							<th colspan="11">
								<input type="text" name="page" placeholder="1">
							</th>
						</tr>
					</tfoot>
					<tbody>
					<?php if ( !empty($this->orders) ):?>
						<?php foreach ($this->orders as $key=>$val):?>
						<tr>
							<td>
								<input type="checkbox" name="check1">
							</td>
							<td><?php echo $val['orderID']?></td>
							<td><?php echo $val['orderName']?></td>
							<td><?php echo $val['predmet']?></td>
							<td><?php echo $val['predmetType']?></td>
							<td><?php echo $val['customerName']?></td>
							<td><?php echo $val['orderDtAdd']?></td>
							<td><?php echo $val['orderDtEnd']?></td>
							<td><?php echo $val['orderCount']?></td>
							<td><span id="<?php echo $key;?>" class="edit" onClick="ShowOrder(this.id);userEditToggle(true)"></span></td>
						</tr>
						<?php endforeach;?>
					<?php endif;?>
					</tbody>
				</table>
			</form>
		</div>
		<div id="footer"></div>
	</div>