
<div id="wrap" class="reg">
<?php if( !isset($this->reg) ){?>
		<form  method="post" class="jClever">
			<h1 class="header">Регистрация нового автора</h1>
			<div class="wrap">
				<?php if( !empty($this->error) ):?>
					<p class="errormsg"><?php echo $this->error;?></p>
				<?php endif;?>
				<div class="reg-user">
					<h2 class="header">Обязательные поля</h2>
					<label>ФИО<sup>*</sup></label><br>
					<input name="fio" type="text" placeholder="Фамилия, имя, отчество"><br>
					<label>Логин<sup>*</sup></label><br>
					<input name="login" type="text" placeholder="Введите желаемый логин"><br>
					<label>Пароль<sup>*</sup></label><br>
					<input name="pass" type="password" placeholder="Введите пароль к аккаунту"><br>
					<label>Повторите пароль<sup>*</sup></label><br>
					<input name="pass1" type="password" placeholder="Повторите введенный пароль"><br>
					<label>Email<sup>*</sup></label><br>
					<input name="email" type="text" placeholder="Введите ваш email"><br>
					<label>Номер мобильного<sup>*</sup></label><br>
					<input name="mobilePhone"type="text" placeholder="+380951234567 - формат номера"><br>
				</div>
				<div class="reg-user">
					<h2 class="header">Дополнительные данные</h2>
					<label>Городской телефон</label><br>
					<input name="phone" type="text" placeholder="Введите ваш городской номер"><br>
					<label>Страница в интернете</label><br>
					<input name="web" type="text" placeholder="Ваша страница в VK, Facebook, ваш сайт..."><br>
					<label>ICQ</label><br>
					<input name="ICQ" type="text" placeholder="Введите ваш номер ICQ"><br>
					<label>Skype</label><br>
					<input name="skype" type="text" placeholder="Введите ваш логин Skype"><br>
					<label>Ваш адрес</label><br>
					<textarea name="adress" placeholder="Введите ваш адрес проживания"></textarea>
				</div><br>
				<div class="reg-user extended">
					<h2 class="header">Выберите вашу специализацию</h2>
					<p><strong>Подсказка:</strong> Вы можете выбрать несколько специализаций просто выбрав их из левого списка. Чтобы удалить лишнюю специализацию нажмите на нее в правом списке.</p>
					<select name="spec[]" multiple="multiple" id="spec">
						<option value="APP|Автоматизация производственных процессов (АПП)">Автоматизация производственных процессов (АПП)</option>
						<option value="Anatomiya|Анатомия">Анатомия</option>
						<option value="AngliyskiyYazik|Английский язык">Английский язык</option>
						<option value="AntikrizisnoeUpravlenie|Антикризисное управление">Антикризисное управление</option>
						<option value="Arhitektura|Архитектура">Архитектура</option>
						<option value="Astronomiya|Астрономия">Астрономия</option>
						<option value="AuditBuhgalterskiyIUpravlencheskiyUchet|Аудит, бухгалтерский и управленческий учет">Аудит, бухгалтерский и управленческий учет</option>
						<option value="AHD|Анализ хозяйственной деятельности">Анализ хозяйственной деятельности</option>
						<option value="BankovskiyIInvesticionniyMenedzhment|Банковский и инвестиционный менеджмент">Банковский и инвестиционный менеджмент</option>
						<option value="BankovskoeDelo|Банковское дело">Банковское дело</option>
						<option value="BZHD|Безопасность жизнедеятельности">Безопасность жизнедеятельности</option>
						<option value="BiznessPlanirovanie|Бизнес планирование">Бизнес-планирование</option>
						<option value="Biologiya|Биология">Биология</option>
						<option value="BuhuchetStatistika|Бухучет, статистика">Бухучет, статистика</option>
						<option value="VSTI|Взаимозаменяемость, Стандартизация, Технические измерения">Взаимозаменяемость, Стандартизация, Технические измерения</option>
						<option value="VED|Внешняя эконом деятельность">Внешняя эконом деятельность</option>
						<option value="Geografiya|География">География</option>
						<option value="Geodeziya|Геодезия">Геодезия</option>
						<option value="Geopolitika|Геополитика">Геополитика</option>
						<option value="Gidravlika|Гидравлика">Гидравлика</option>
						<option value="GostinichnoeDelo|Гостиничное дело">Гостиничное дело</option>
						<option value="GrazhdanskoePravo|Граждансое право">Граждансое право</option>
						<option value="Deloproizvodstvo|Делопроизводство">Делопроизводство</option>
						<option value="DengiKreditBanki|Деньги, кредит, банки">Деньги, кредит, банки</option>
						<option value="DetaliMashin|Детали машин">Детали машин</option>
						<option value="Dizain|Дизайн">Дизайн</option>
						<option value="DoshkolnayaPedagogika|Дошкольная педагогика">Дошкольная педагогика</option>
						<option value="ZhilishnoePravo|Жилищное право">Жилищное право</option>
						<option value="Zhurnalistika|Журналистика">Журналистика</option>
						<option value="ZemelnoePravo|Земельное право">Земельное право</option>
						<option value="InvesticionniyMenedzhment|Инвестиционный менеджмент">Инвестиционный менеджмент</option>
						<option value="Investicii|Инвестиции">Инвестиции</option>
						<option value="InzhenernayaGrafika|Инженерная графика">Инженерная графика</option>
						<option value="InostrannieYaziki|Иностранные языки">Иностранные языки</option>
						<option value="InformatikaIProgrammirovanie|Информатика и программирование">Информатика и Программирование</option>
						<option value="Istoriya|История">История</option>
						<option value="KommercheskayaDeyatelnost|Коммерческая деятельность">Коммерческая деятельность</option>
						<option value="Konfliktologiya|Конфликтология">Конфликтология</option>
						<option value="Kriminalistika|Криминалистика">Криминалистика</option>
						<option value="Kulinariya|Кулинария">Кулинария</option>
						<option value="KulturaIIskusstvo|Культура и искуство">Культура и искуство</option>
						<option value="Kulturologiya|Культурология">Культурология</option>
						<option value="Lingvistika|Лингвистика">Лингвистика</option>
						<option value="Literatura|Литература">Литература</option>
						<option value="Logika|Логика">Логика</option>
						<option value="Logistika|Логистика">Логистика</option>
						<option value="Logopediya|Логопедия">Логопедия</option>
						<option value="Makroekonomika|Макроэкономика">Макроэкономика</option>
						<option value="Marketing|Маркетинг">Маркетинг</option>
						<option value="Matematika|Математика">Математика</option>
						<option value="Medicina|Медицина">Медицина</option>
						<option value="MezhdunarodnieOtnosheniya|Международные отношения">Международные отношения</option>
						<option value="Menedzhment|Менеджмент">Менеджмент</option>
						<option value="Mehanika|Механика">Механика</option>
						<option value="Mikroekonomika|Микроэкономика">Микроэкономика</option>
						<option value="MunicipalnoePravo|Муницепальное право">Муницепальное право</option>
						<option value="Nalogi|Налоги">Налоги</option>
						<option value="NemeckiyYazik|Немецкий язык">Немецкий язык</option>
						<option value="OrganizaciyaTrudaIProizvodstvo|Организация труда и производство">Организация труда и производство</option>
						<option value="OsnoviKonstruiroravaniya|Основы конструирования">Основы конструирования</option>
						<option value="OsnoviPredprinimatelstva|Основы предпринимательства">Основы предпринимательства</option>
						<option value="OhranaPrirodi|Охрана природы">Охрана природы</option>
						<option value="OhranaTruda|Охрана труда">Охрана труда</option>
						<option value="Pedagogika|Педагогика">Педагогика</option>
						<option value="Politologiya|Политология">Политология</option>
						<option value="Pravo|Право">Право</option>
						<option value="Predprinimatelstvo|Предпринимательство">Предпринимательство</option>
						<option value="Promishlennost|Промышленность">Промышленность</option>
						<option value="ProcessiIApparatiPishevoiPromishlennosti|Процессы и аппараты пищевой промышленности">Процессы и аппараты пищевой промышленности</option>
						<option value="Psihologiya|Психология">Психология</option>
						<option value="RadiosvazIRadiotehnika|Радиосвязь и радиотехника">Радиосвязь и радиотехника</option>
						<option value="Raznoe|Разное">Разное</option>
						<option value="PeklamaPR|Реклама, PR">Реклама, PR</option>
						<option value="RusskiyYazikILiteratura|Русский язык и литература">Русский язык и литература</option>
						<option value="SelskoeHozyaistvo|Сельское хозяйство">Сельское хозяйство</option>
						<option value="SistemiPeredachiISistemiKommutacii|Системы передачи и системы коммутации">Системы передачи и системы коммутации</option>
						<option value="Sopromat|Сопромат">Сопромат</option>
						<option value="SocialnayaRabota|Социальная работа">Социальная работа</option>
						<option value="Sociologiya|Социология">Социология</option>
						<option value="SportITurizm|Спорт и туризм">Спорт и туризм</option>
						<option value="Statistika|Статистика">Статистика</option>
						<option value="StrategicheskiyMarketing|Стратегический маркетинг">Стратегический маркетинг</option>
						<option value="StrategicheskiyMenedzhment|Стратегический менеджмент">Стратегический менеджмент</option>
						<option value="Strahovanie|Страхование">Страхование</option>
						<option value="Stroitelstvo|Строительство">Строительство</option>
						<option value="SudebnayaBuhgaltiriya|Судебная бухгалтерия">Судебная бухгалтерия</option>
						<option value="Telekommunikaciya|Телекоммуникация">Телекоммуникация</option>
						<option value="TeoreticheskayaMehanika|Теоретическая механика">Теоретическая механика</option>
						<option value="TeoriyaGosudarstvaIPrava|Теория государства и права">Теория государства и права</option>
						<option value="TeoriyaMashinIMehanizmov|Теория машин и механизмов (ТММ)">Теория машин и механизмов (ТММ)</option>
						<option value="Teplotehnika|Теплотехника">Теплотехника</option>
						<option value="Teploenergetika|Теплоэнергетика">Теплоэнергетика</option>
						<option value="Tehnicheskie|Технические">Технические</option>
						<option value="TehnologiyaMashinostroeniya|Технология машиностроения">Технология машиностроения</option>
						<option value="Tovarovedenie|Товароведение">Товароведение</option>
						<option value="Turizm|Туризм">Туризм</option>
						<option value="UgolovnoePravo|Уголовное право">Уголовное право</option>
						<option value="UgolovniyProcess|Уголовный процесс">Уголовный процесс</option>
						<option value="UkrainskiyYazikILiteratura|Украинский язык и литература">Украинский язык и литература</option>
						<option value="UpravlenieZatratami|Управление затратами">Управление затратами</option>
						<option value="UpravlenieLogistikoi|Управление логистикой">Управление логистикой</option>
						<option value="UpravleniePersonalom|Управление персоналом">Управление персоналом</option>
						<option value="UpravlenieProektami|Управление проектами">Управление проектами</option>
						<option value="UpravlenieIssledovaniyami|Управление исследованиями">Управление исследованиями</option>
						<option value="UpravlencheskiyUchet|Управленческий учет">Управленческий учет</option>
						<option value="Fizika|Физика">Физика</option>
						<option value="FizkulturaISport|Физкультура и спорт">Физкультура и спорт</option>
						<option value="Filologiya|Филология">Филология</option>
						<option value="Filosofiya|Философия">Философия</option>
						<option value="FinansoviyAnaliz|Финансовый анализ">Финансовый анализ</option>
						<option value="FinansiIKredit|Финансы и кредит">Финансы и кредит</option>
						<option value="FrancuzskiyYazik|Французский язык">Французский язык</option>
						<option value="Himiya|Химия">Химия</option>
						<option value="CeniICenoobrazovanie|Цены и ценообразование">Цены и ценообразование</option>
						<option value="Cherchenie|Черчение">Черчение</option>
						<option value="Ekologiya|Экология">Экология</option>
						<option value="Ekonomika|Экономика">Экономика</option>
						<option value="EkonomikaPredpriyatiya|Экономика предприятия">Экономика предприятия</option>
						<option value="EkonomicheskayaTeoriya|Экономическая теория">Экономическая теория</option>
						<option value="EkonomicheskieDisciplini|Экономические дисциплины">Экономические дисциплины</option>
						<option value="EkonomicheskiyAnaliz|Экономический анализ">Экономический анализ</option>
						<option value="Ekskursovedenie|Экскурсоведение">Экскурсоведение</option>
						<option value="ElektronikaIRadiotehnika|Электроника и радиотехника">Электроника и радиотехника</option>
						<option value="Elektrotehnika|Электротехника">Электротехника</option>
						<option value="Elektroenergetika|Электроэнергетика">Электроэнергетика</option>
						<option value="Energetika|Энергетика">Энергетика</option>
						<option value="Energosnabzhenie|Энергоснабжение">Энергоснабжение</option>
						<option value="EtikaIEstetika|Этика и эстетика">Этика и эстетика</option>
						<option value="UridicheskieDisciplini|Юридические дисциплины">Юридические дисциплины</option>
						<option value="Urisprudenciya|Юриспруденция">Юриспруденция</option>
					</select>
					<script type="text/javascript">
						$('#spec').multiSelect();
					</script>
					<br>
					<input name="reg" type="submit" value="Зарегистрировать">
				</div>
			</div>
		</form>
<?php }else echo "<p class='success'>Вы успешно зарегистрировались</p>";?>
	</div>